-- Add stock_score column to articles table
ALTER TABLE articles ADD COLUMN stock_score INTEGER;

-- Add index for better performance
CREATE INDEX idx_articles_stock_score ON articles(stock_score);

-- Add comment
COMMENT ON COLUMN articles.stock_score IS 'Stock score rating from 1-100, generated by AI analysis';
